# Generated by Django 4.2.4 on 2026-03-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserRemedyOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_email", models.EmailField(db_index=True, max_length=254)),
                (
                    "remedy_name",
                    models.CharField(
                        db_index=True,
                        help_text="Herb or remedy name, stored lowercase.",
                        max_length=200,
                    ),
                ),
                (
                    "condition_treated",
                    models.CharField(
                        help_text="The symptom or condition the remedy was used for.",
                        max_length=300,
                    ),
                ),
                (
                    "efficacy_score",
                    models.IntegerField(
                        choices=[
                            (1, "1 — No effect"),
                            (2, "2 — Minimal improvement"),
                            (3, "3 — Moderate improvement"),
                            (4, "4 — Good improvement"),
                            (5, "5 — Excellent — fully resolved"),
                        ],
                        help_text="1–5 scale of how well the remedy worked.",
                    ),
                ),
                (
                    "improvement_noted",
                    models.BooleanField(
                        default=False,
                        help_text="Quick boolean: did the user notice improvement?",
                    ),
                ),
                (
                    "side_effects_reported",
                    models.TextField(
                        blank=True,
                        help_text="Free-text description of any side effects experienced.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional user notes about the remedy experience.",
                    ),
                ),
                (
                    "tried_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when feedback was submitted.",
                    ),
                ),
            ],
            options={
                "db_table": "user_remedy_outcomes",
                "ordering": ["-tried_at"],
                "indexes": [
                    models.Index(
                        fields=["user_email", "remedy_name"],
                        name="user_remedy_user_em_4be1cd_idx",
                    )
                ],
            },
        ),
    ]
